### ISSUE TITLE
Output processing without html (Ubuntu)

### ISSUE THREAD

**Issue by TaehyungKwon** [nselem/evomining#2]
Dear all,

I tried to figure out how to process the output of the latest Evomining (2.0) without HTML.
I want to predict putative BGCs from the run. However, maybe because I am not familiar with docker, the only way seems to be using web interface which currently shows "under construction" in tab 2 and tab 3. Could you kindly guide me on how to process the BGC prediction within the command-line interface on docker?
Thanks!

**Comment by nselem** [comment]
Hello Tae
You can use the microreact compatible output. If you wish we can set up a skype meeting to better understand your problem.

**Comment by TaehyungKwon** [comment]
Please forgive me for not understanding what you mean. Could you explain where the predicted results are stored in the docker container? I haven't found BGC prediction in the result directory even when I used a sample data.

**Comment by nselem** [comment]
BGCs are not predicted, what it is predicted is enzymes that belong to BGCs, these enzymes are those ones that are marked with green color. What I said is that you can see them more clearly if you use microreact. You can upload the .cvs and .nwk that is located in the blast/seqf/tree directory into microreact and get a better visualization of the tree. Also, If you have more doubts we can set a time and discuss them y skype

**Comment by nselem** [comment]
You need the html view, it is imposible just with the command line.

**Comment by TaehyungKwon** [comment]
Thank you Nelly. It helped me a lot!
